[package]
name = "questions_answered"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.39", features = ["full"] }
warp = "0.3"
handle-errors = { path = "handle-errors" }
