version: '3.8'
services:
  postgres:
    container_name: postgresql
    image: cgr.dev/chainguard/postgres:latest
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ksedrocks
      POSTGRES_DB: qa_db
    volumes:
      - "./data:/var/lib/postgresql/data"
    restart: unless-stopped
